import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";
import AuthContextProvider from "@/providers/auth-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <div className="dark:bg-dark dark:text-light min-h-screen duration-500">
            <div className="container mx-auto text-slate-900 px-2">
              <div className="">
                <Navbar />
                {children}
                <Footer />
              </div>
            </div>
          </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
